baseURL = '/'
languageCode = 'cs'
defaultContentLanguage = "cs"
hasCJKLanguage = true
enableEmoji = true
title = 'd277'
copyright = 'David Marek'
theme = 'hugo-theme-itheme'
paginate = 6
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'floyd.li@outlook.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/floyd-li'
  [[params.blogroll]]
    name = '驭风笔记'
    url = 'https://yufengbiji.com/'
